export const DEWORMING_ADD_REQUEST = 'DEWORMING_ADD_REQUEST'
export const DEWORMING_ADD_SUCCESS = 'DEWORMING_ADD_SUCCESS'
export const DEWORMING_ADD_FAIL = 'DEWORMING_ADD_FAIL'

export const DEWORMING_UPDATE_REQUEST = 'DEWORMING_UPDATE_REQUEST'
export const DEWORMING_UPDATE_SUCCESS = 'DEWORMING_UPDATE_SUCCESS'
export const DEWORMING_UPDATE_FAIL = 'DEWORMING_UPDATE_FAIL'

export const DEWORMING_DELETE_REQUEST = 'DEWORMING_DELETE_REQUEST'
export const DEWORMING_DELETE_SUCCESS = 'DEWORMING_DELETE_SUCCESS'
export const DEWORMING_DELETE_FAIL = 'DEWORMING_DELETE_FAIL'
