export const INVOICES_LIST_REQUEST = 'INVOICES_LIST_REQUEST'
export const INVOICES_LIST_SUCCESS = 'INVOICES_LIST_SUCCESS'
export const INVOICES_LIST_FAIL = 'INVOICES_LIST_FAIL'

export const INVOICE_DETAILS_REQUEST = 'INVOICE_DETAILS_REQUEST'
export const INVOICE_DETAILS_SUCCESS = 'INVOICE_DETAILS_SUCCESS'
export const INVOICE_DETAILS_FAIL = 'INVOICE_DETAILS_FAIL'
