export const PET_LIST_REQUEST = 'PET_LIST_REQUEST'
export const PET_LIST_SUCCESS = 'PET_LIST_SUCCESS'
export const PET_LIST_FAIL = 'PET_LIST_FAIL'

export const PET_CREATE_REQUEST = 'PET_CREATE_REQUEST'
export const PET_CREATE_SUCCESS = 'PET_CREATE_SUCCESS'
export const PET_CREATE_FAIL = 'PET_CREATE_FAIL'

export const PET_UPDATE_REQUEST = 'PET_UPDATE_REQUEST'
export const PET_UPDATE_SUCCESS = 'PET_UPDATE_SUCCESS'
export const PET_UPDATE_FAIL = 'PET_UPDATE_FAIL'

export const PET_DELETE_REQUEST = 'PET_DELETE_REQUEST'
export const PET_DELETE_SUCCESS = 'PET_DELETE_SUCCESS'
export const PET_DELETE_FAIL = 'PET_DELETE_FAIL'

export const PET_DETAILS_REQUEST = 'PET_DETAILS_REQUEST'
export const PET_DETAILS_SUCCESS = 'PET_DETAILS_SUCCESS'
export const PET_DETAILS_FAIL = 'PET_DETAILS_FAIL'

export const PET_BREED_REQUEST = 'PET_BREED_REQUEST'
export const PET_BREED_SUCCESS = 'PET_BREED_SUCCESS'
export const PET_BREED_FAIL = 'PET_BREED_FAIL'
