export const VACCINE_ADD_REQUEST = 'VACCINE_ADD_REQUEST'
export const VACCINE_ADD_SUCCESS = 'VACCINE_ADD_SUCCESS'
export const VACCINE_ADD_FAIL = 'VACCINE_ADD_FAIL'

export const VACCINE_UPDATE_REQUEST = 'VACCINE_UPDATE_REQUEST'
export const VACCINE_UPDATE_SUCCESS = 'VACCINE_UPDATE_SUCCESS'
export const VACCINE_UPDATE_FAIL = 'VACCINE_UPDATE_FAIL'

export const VACCINE_DELETE_REQUEST = 'VACCINE_DELETE_REQUEST'
export const VACCINE_DELETE_SUCCESS = 'VACCINE_DELETE_SUCCESS'
export const VACCINE_DELETE_FAIL = 'VACCINE_DELETE_FAIL'
